#!/bin/bash
export PYTHONIOENCODING=UTF-8
SEX=`cat $PWD/sex | sort -R | head -1`
COUNTRY=$1
FAKER=`cat $PWD/countrycode/$COUNTRY`
PWD=`pwd`
FIRSTNAME=`faker -l $FAKER first_name_$SEX`
USERNAME=$RANDOM$FIRSTNAME

MOBILE=`faker -l $FAKER msisdn`
UA=`cat $PWD/user-agent.txt | sort -R | head -1`$RANDOM

LASTNAME=`faker -l $FAKER last_name_$SEX`
CITY=`faker -l $FAKER city`
YEAR=`shuf -i 1972-1992 -n 1`
MONTH=`shuf -i 1-9 -n 1`
DATE=`shuf -i 10-28 -n 1`
ADDRESS=`faker -l $FAKER street_address`
ZIPCODE=`faker -l $FAKER postcode`

NOW=`date +%Y-%m-%d`
DOMAIN=`cat $PWD/tempmail/fmgdomain.txt | sort -R | head -1`

EMAIL=$USERNAME@$DOMAIN



# http  "http://www.fakemailgenerator.com/#/$DOMAIN/$USERNAME/"

gnome-terminal -- google-chrome --new-window "http://www.fakemailgenerator.com/#/$DOMAIN/$USERNAME/"

sleep 10

wmctrl -ic "$(wmctrl -l | grep 'Google Chrome' | tail -1 | awk '{ print $1 }')"

echo $UA > $PWD/ua

echo username=$USERNAME'&'email=$EMAIL'&'secemail=$EMAIL'&'password=$USERNAME'&'country=$COUNTRY'&'conditions=1'&'mobile=$MOBILE'&'country_prefix=1'&'email_code=1111 > $PWD/step1

curl  -s -k  -X $'POST' \
    -H "@$PWD/ua" -H $'Referer: https://www.videoslots.com/registration1/' -H $'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H $'X-Requested-With: XMLHttpRequest' \
    --data-binary "@$PWD/step1"  -c /tmp/cookie \
    $'https://www.videoslots.com/phive/modules/Micro/registration_new.php?step1=true&lang=en'



echo -e "var fmg = require('fmg2');\n\nvar watcher = fmg.watch('$EMAIL');\nwatcher.once('email', function(email){\n    console.log('GOT EMAIL', email);\n    watcher.stop();\n});\n\nwatcher.on('error', function(err){\n    throw err;\n});"  > fmg.js

node fmg.js > fmglist

html2dic fmglist > fmgid



FMGID=`sed -n '35p' fmgid`

curl "http://www.fakemailgenerator.com/email/cuvox.de/welf1929/message-$FMGID/" > email

html2dic email > email2

EMAILCODES=`sed -n '13p' email2`


echo firstname=$FIRSTNAME'&'lastname=$LASTNAME'&'address=$ADDRESS'&'zipcode=$ZIPCODE'&'city=$CITY'&'newsletter=1'&'over18=1'&'bonus_code=CM45'&'sex=$SEX'&'preferred_lang=en'&'dob=$YEAR-0$MONTH-$DATE'&'birthyear=$YEAR'&'birthmonth=0$MONTH'&'birthdate=$DATE'&'email_code=$EMAILCODES'&'currency=GBP > $PWD/step2




curl  -s -k  -X $'POST' \
    -H "@$PWD/ua" -H $'Referer: https://www.videoslots.com/en/registration2/' -H $'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H $'X-Requested-With: XMLHttpRequest' \
    -b /tmp/cookie -c /tmp/cookie \
    --data-binary "@$PWD/step2" \
    $'https://www.videoslots.com/phive/modules/Micro/registration_new.php?lang=en' 

curl  -s -k  -X $'POST' \
    -H $'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0' -H $'Referer: https://www.videoslots.com/account/' -H $'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H $'X-Requested-With: XMLHttpRequest' \
    -b /tmp/cookie -c /tmp/cookie \
    --data-binary $'aid=323&action=use-trophy-award&lang=en' \
    $'https://www.videoslots.com/phive/modules/Micro/ajax.php'

curl  -s -k  -X $'POST' \
    -H $'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0'  -H $'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H $'X-Requested-With: XMLHttpRequest' \
     -b /tmp/cookie -c /tmp/cookie \
    --data-binary $'aid=324&action=use-trophy-award&lang=en' \
    $'https://www.videoslots.com/phive/modules/Micro/ajax.php'










echo -----------------------------------------------------------
echo username = $USERNAME 
echo email = $EMAIL 
echo country = $COUNTRY 
echo mobile = $MOBILE
echo firstname = $FIRSTNAME 
echo lastname = $LASTNAME 
echo sex = $SEX 
echo birth = $YEAR-0$MONTH-$DATE 
echo address = $ADDRESS city = $CITY zipcode = $ZIPCODE
echo -----------------------------------------------------------
echo $USERNAME >> $PWD/accounts/$COUNTRY-$NOW.txt

echo ------------------------------------------------------------------------------------------------------ >> $PWD/accounts/info.txt
echo username = $USERNAME >> $PWD/accounts/info.txt
echo email = $EMAIL >> $PWD/accounts/info.txt
echo country = $COUNTRY >> $PWD/accounts/info.txt
echo mobile = $MOBILE >> $PWD/accounts/info.txt
echo firstname = $FIRSTNAME >> $PWD/accounts/info.txt
echo lastname = $LASTNAME >>$PWD/accounts/info.txt
echo sex = $SEX >> $PWD/accounts/info.txt
echo birth = $YEAR-0$MONTH-$DATE >> $PWD/accounts/info.txt
echo address = $ADDRESS city = $CITY zipcode = $ZIPCODE >> $PWD/accounts/info.txt
echo ------------------------------------------------------------------------------------------------------ >> $PWD/accounts/info.txt

gnome-terminal -- firefox --new-window 'https://videoslots.com'

sleep 20


WID=`xdotool search --name Mozilla`
xdotool windowfocus $WID
xdotool mousemove 781 240 click 1
xdotool type $USERNAME
xdotool key Tab
xdotool type $USERNAME
xdotool mousemove 1064 287 click 1
sleep 3
xdotool mousemove 61 148 click 1 






