#!/bin/bash

export PYTHONIOENCODING=UTF-8
UA=`faker user_agent`
#PWD=`pwd`
YEAR=`shuf -i 1972-1992 -n 1`
MONTH=`shuf -i 1-9 -n 1`
DATE=`shuf -i 10-28 -n 1`
DOMAIN=`cat $PWD/yandomain.txt | shuf | head -1`
USERNAME=`faker first_name``cat /dev/urandom | tr -dc "a-z" | fold -w 1 | head -1``cat /dev/urandom | tr -dc "a-z" | fold -w 1 | head -1`
EMAIL=$USERNAME@$DOMAIN
LTNAME=`faker last_name`


#curl -L  -s   -X $'GET' \
#    -H $'Host: latestcasinobonuses.com' -H "User-Agent: $UA" -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H $'Accept-Language: en,en-US;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Upgrade-Insecure-Requests: 1' -H $'Connection: close' -c $PWD/cookie  \    $'https://latestcasinobonuses.com/url?casino=1087'

#html2dic cookie > bet
#TOKEN=`sed -n '47p' bet`


curl -H 'PddToken: 4DZWPZBDRXDZUYFPS2RNW3NSTZSWEKPMVKN3EFKL6T3CEN34NJMQ' -d "domain=$DOMAIN&login=$USERNAME&password=h123085858&iname=$USERNAME&fname=$LTNAME&enabled=yes&birth_date=$YEAR-$MONTH-$DATE&sex=1&hintq=pet's nmame ???&hinta=$USERNAME" 'https://pddimp.yandex.ru/api2/admin/email/add'

echo $EMAIL
